import Head from 'next/head';
import Image from 'next/image';
import Container from '../components/ui/Container';
import Slider from '../components/ui/slider';

export default function Home() {
  return (
    <div>
      <Head>
        <title>TITLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className=" pt-14 pb-12 px-6">
          <b>T I T L E</b>
          <p className="py-4">어떤 말을 넣지?!!?!?!?!</p>
          {/* <Slider height="small" /> */}
          {/* <BottomInfo className="mt-40 mb-8" /> */}
        </div>
      </Container>
    </div>
  );
}
