import Head from 'next/head';
import Container from '../components/ui/Container';

export default function Home() {
  return (
    <>
      <Head>
        <title>주사기</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="stock-title" />
        <meta name="og:description" content="Can draw charts and view news" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className=" pt-14 pb-12 px-6">
          <h2>주 사 기</h2>
          <p className="py-4">MAIN PAGE</p>
          {/* <Slider height="small" /> */}
          {/* <BottomInfo className="mt-40 mb-8" /> */}
        </div>
      </Container>
    </>
  );
}
